package com.example.composelocationweather.util


object TestTags {
    const val CURRENT_TEMP_TEXT = "CURRENT_TEMP_TEXT"
    const val CURRENT_TEMP_DESC = "CURRENT_TEMP_DESC"
    const val FORECAST_LIST = "FORECAST_LIST"
    const val LOCATION_NAV_FAB = "LOCATION_NAV_FAB"
    const val CURRENT_MIN_TEMP_TEXT = "CURRENT_MIN_TEMP_TEXT"
    const val CURRENT_MAX_TEMP_TEXT = "CURRENT_MAX_TEMP_DESC"
    const val CURRENT_TEMP_INFO_TEXT = "CURRENT_TEMP_INFO_TEXT"
    const val LAST_SYNC_TIME_TEXT = "LAST_SYNC_TIME_TEXT"

    const val SAVE_LOCATION_TEXT = "SAVE_LOCATION_TEXT"
    const val NAVIGATE_TO_MAP_TEXT = "NAVIGATE_TO_MAP_TEXT"
    const val NAVIGATE_TO_LOCATIONS_TEXT = "NAVIGATE_TO_LOCATIONS_TEXT"

    const val WEATHER_SCREEN_SNACK_BAR = "WEATHER_SCREEN_SNACK_BAR"
    const val FAVORITE_LOCATION_TITLE = "FAVORITE_LOCATION_TITLE"
}
